apiVersion: v1
kind: Service
metadata:
  name: contacts-mango-cluster-ip-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    component: mango-database
  ports:
    - port: 27017
      targetPort: 27017