apiVersion: v1
kind: Service
metadata:
  name: contact-frontend-cluster-ip-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    component: contacts-frontend
  ports:
    - port: 4200
      targetPort: 4200
