apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mango-persistent-volume-claim
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
   requests:
    storage: 128Mi